networks:
  ssr:

services:

  db:
    image: redis
    restart: "no"
    ports:
     - 172.17.0.1:6379:6379
    volumes:
      - /srv/docker/ssr/redis/data:/data

  webserver:
    image: fullaxx/ss_webserver
    restart: "no"
    depends_on:
     - db
    environment:
     - REDIS_URL=redis://172.17.0.1:6379?db=0
     - JSON_FETCH_INTERVAL=3000
     - MARKET_DATA_CREATE_INTERVAL=2
    ports:
     - 172.17.0.1:7000:80
    volumes:
     - /srv/docker/ssr/config:/config

  yfinance:
    image: fullaxx/ss_yfinance
    restart: "no"
    depends_on:
     - db
    environment:
     - REDIS_URL=redis://172.17.0.1:6379?db=0
     - YFINANCE_REQUEST_INTERVAL=15
    volumes:
     - /srv/docker/ssr/config:/config

  alpaca:
    image: fullaxx/ss_alpaca
    restart: "no"
    depends_on:
     - db
    environment:
     - REDIS_URL=redis://172.17.0.1:6379?db=0
     - ALPACA_APIKEY=XXXXXXXXX
     - ALPACA_SECRET=XXXXXXXXX
     - STOCK_TRADES=AAPL,AMZN,ARM,AVGO,AXON,BLK,CART,CAT,DDOG,GOOGL,META,MSFT,MU,NFLX,NVDA,ORCL,PLTR,POWL,SMCI,TSLA,TSM,VRT,VST,WMT
     - CRYPTO_TRADES=BTC/USD,ETH/USD,LTC/USD,DOGE/USD
    volumes:
     - /srv/docker/ssr/config:/config
